FROM node:9.11.1-alpine

# Create app directory
WORKDIR /app

# install mocha for test purpose
RUN npm install mocha@latest -g

# install eslint
RUN npm install eslint@latest -g

# install nsp
RUN npm install nsp@latest -g

# A wildcard is used to copy the package files.
COPY package.json /app/package.json

# Install app dependencies
# For production, use npm install --only=production
RUN npm install
RUN mv /app/node_modules /node_modules

# Bundle app source
COPY . /app

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "test"]


